import os

from workspace_analyzer import (
    WorkspaceAnalyzer
)


def create_workspace():

    analyzer = WorkspaceAnalyzer()

    print(
        "\n========================="
    )

    print(
        "AUTO WORKSPACE BUILDER"
    )

    print(
        "========================="
    )

    project_name = input(
        "\nProject Name:\n"
    ).strip()

    modules = analyzer.analyze(
        project_name
    )

    root_folder = (
        project_name
        .replace(" ", "-")
        .lower()
    )

    os.makedirs(
        root_folder,
        exist_ok=True
    )

    os.makedirs(
        f"{root_folder}/backend",
        exist_ok=True
    )

    os.makedirs(
        f"{root_folder}/frontend",
        exist_ok=True
    )

    os.makedirs(
        f"{root_folder}/database",
        exist_ok=True
    )

    for module in modules:

        os.makedirs(
            f"{root_folder}/{module}",
            exist_ok=True
        )

    readme = (
        f"# {project_name}\n\n"
        f"Generated by "
        f"Auto Workspace Builder\n"
    )

    with open(
        f"{root_folder}/README.md",
        "w",
        encoding="utf-8"
    ) as file:

        file.write(
            readme
        )

    print(
        "\nWorkspace Created:"
    )

    print(
        root_folder
    )

    print(
        "\nGenerated Modules:"
    )

    for module in modules:

        print(
            f"- {module}"
        )


if __name__ == "__main__":

    create_workspace()